### ISSUE TITLE
wrong-type-argument org-roam-node nil

### ISSUE THREAD

**Issue by lroolle** [tefkah/org-roam-timestamps#13]
```elisp
Error (before-save-hook): Error a hook "org-roam-timestamps--on-save" because: (wrong-type-argument org-roam-node nil)
```

**Comment by stites** [comment]
I just got this, but I tried to add a workaround, and now I can't reproduce this. When did this happen to you? I thought it was "on save when there when I was on a header that was not an org-roam-node" but apparently, this is not the behavior. I only get this when I reproduce #12. Can you confirm this is not a duplicate?

**Comment by dmitrym0** [comment]
This just started happening to me as well. I noticed it when doing a new capture.

**Comment by lroolle** [comment]
Hi @stites, I checked out  your commit, the  seems like the `Error` message doesn't show again,  thanks.

@ThomasFKJorna   #14 can be merged.

**Comment by bitozoid** [comment]
@tefkah Works for me.
